"""Add item_id to Payment model

Revision ID: 99320f6c8e93
Revises: 0c563c297b6f
Create Date: 2024-08-16 08:27:14.578021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99320f6c8e93'
down_revision = '0c563c297b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_payment_item_id', 'item', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_item_id', type_='foreignkey')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
