"""Create reviews table

Revision ID: f425db5b43f4
Revises: 06dd5e403ad8
Create Date: 2024-08-07 07:20:30.443624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f425db5b43f4'
down_revision = '06dd5e403ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewName', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reviewMessage', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
